### ISSUE TITLE
Decouple the handling of pre-analytics in fluffy

### ISSUE THREAD

**Issue by karlnyr** [J35P312/fluffy#5]
There has been some issues lately where samplesheets are getting updated in workflows, hindering smooth processing done by fluffy. I believe that fluffy should be turned into a tool where it only handles the analysis of data. That way, a monolithic solution such as `cg` can handle all the pre-analytical parts of this tool - thus letting fluffy do what fluffy does best - analyse the data.

**Comment by J35P312** [comment]
Hello there!
I have understood that some sort of samplesheet generator will be added into CG, which will generate samplesheets suitable for running fluffy. Feel free to comment if you have any other specific comments regarding the pre-analytical parts!

**Comment by karlnyr** [comment]
It would seem like `samplesheet.py` is the only part I would say is non-fluffy-worthy. Otherwise Fluffy is doing what fluffy knows best - being a snail. 👍

**Comment by J35P312** [comment]
Thank you, I agree!
For now, the samplesheet.py issues are solved in cg!
Maybe some day we will move away from the samplesheet...
