### ISSUE TITLE
blacklist bed file

### ISSUE THREAD

**Issue by Sondr11** [J35P312/fluffy#7]
Hello
blacklist bed file, is it generated with WisecondorX for each sample or referrent?

**Comment by J35P312** [comment]
Hello!
You will need to download the blacklist bed; there is one for hg38 in the wisecondorX repository:

https://github.com/CenterForMedicalGeneticsGhent/WisecondorX/tree/master/example.blacklist

Good luck!

**Comment by Sondr11** [comment]
I used hg19. How can I creat file blacklist bed?

**Comment by J35P312** [comment]
Then I would reccomend you to start with the ENCODE blacklist, which is available for hg19:

https://www.encodeproject.org/annotations/ENCSR636HFF/

You could probably improve the blacklist by removing regions that have too high, low or variable coverage amongst your samples, but I have nott ried doing so yet.

**Comment by Sondr11** [comment]
Thank you very much
